# coding: utf-8
#
# user-graph need to be generated by the following script
# tools/generate-u-u-matrix.py
import os
import numpy as np
import scipy.sparse as sp
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn.conv import MessagePassing
from torch_geometric.utils import remove_self_loops, add_self_loops, degree
import torch_geometric

from common.abstract_recommender import GeneralRecommender
from common.loss import BPRLoss, EmbLoss
from common.init import xavier_uniform_initialization


class MENTOR(GeneralRecommender):
    """
        MENTOR模型的初始化函数。

        参数:
        - config: 包含模型配置的字典。
        - dataset: 数据集对象。

        该函数主要负责根据配置初始化模型的参数和结构，包括嵌入层、图卷积网络(GCN)等组件的创建和配置。
    """
    def __init__(self, config, dataset):
        # 调用父类的初始化方法
        super(MENTOR, self).__init__(config, dataset)

        # 初始化用户和物品的数量
        num_user = self.n_users
        num_item = self.n_items
        # 初始化批处理大小（未使用）
        batch_size = config['train_batch_size']
        # 初始化嵌入层的维度
        dim_x = config['embedding_size']
        # 特征嵌入的维度
        self.feat_embed_dim = config['feat_embed_dim']
        # 多模态层的数量
        self.n_layers = config['n_mm_layers']
        # K近邻图的K值
        self.knn_k = config['knn_k']
        # 图像模态的权重
        self.mm_image_weight = config['mm_image_weight']

        # 设置批处理大小、用户数、物品数等属性
        self.batch_size = batch_size
        self.num_user = num_user
        self.num_item = num_item
        # 初始化其他参数，如K近邻图的K值、聚合模式等
        self.k = 40
        self.aggr_mode = 'add'
        self.dataset = dataset
        self.dropout = config['dropout']
        self.reg_weight = config['reg_weight']
        self.align_weight = config['align_weight']
        self.mask_weight_g = config['mask_weight_g']
        self.mask_weight_f = config['mask_weight_f']
        self.temp = config['temp']
        self.drop_rate = 0.1
        # 初始化视觉和文本表示以及偏好相关的属性
        self.v_rep = None
        self.t_rep = None
        self.v_preference = None
        self.t_preference = None
        self.id_preference = None
        # 嵌入和特征的维度
        self.dim_latent = 64
        self.dim_feat = 128
        # 多模态邻接矩阵
        self.mm_adj = None

        # 创建多层感知机(MLP)
        self.mlp = nn.Linear(2 * dim_x, 2 * dim_x)

        # 构建数据集路径并加载用户图字典
        dataset_path = os.path.abspath(config['data_path'] + config['dataset'])
        self.user_graph_dict = np.load(os.path.join(dataset_path, config['user_graph_dict_file']),
                                       allow_pickle=True).item()

        # 多模态邻接矩阵文件路径
        mm_adj_file = os.path.join(dataset_path, 'mm_adj_{}.pt'.format(self.knn_k))

        # 如果存在预训练的视觉或文本特征，初始化相应的嵌入层
        if self.v_feat is not None:
            self.image_embedding = nn.Embedding.from_pretrained(self.v_feat, freeze=False)
            self.image_trs = nn.Linear(self.v_feat.shape[1], self.feat_embed_dim)
        if self.t_feat is not None:
            self.text_embedding = nn.Embedding.from_pretrained(self.t_feat, freeze=False)
            self.text_trs = nn.Linear(self.t_feat.shape[1], self.feat_embed_dim)

        # 如果存在多模态邻接矩阵文件，加载之；否则，构建新的邻接矩阵
        if os.path.exists(mm_adj_file):
            self.mm_adj = torch.load(mm_adj_file).to(self.device)
        else:
            if self.v_feat is not None:
                indices, image_adj = self.get_knn_adj_mat(self.image_embedding.weight.detach())
                self.mm_adj = image_adj
            if self.t_feat is not None:
                indices, text_adj = self.get_knn_adj_mat(self.text_embedding.weight.detach())
                self.mm_adj = text_adj
            if self.v_feat is not None and self.t_feat is not None:
                self.mm_adj = self.mm_image_weight * image_adj + (1.0 - self.mm_image_weight) * text_adj
                del text_adj
                del image_adj
            torch.save(self.mm_adj, mm_adj_file)

        # 构建训练交互的边索引
        train_interactions = dataset.inter_matrix(form='coo').astype(np.float32)
        edge_index = self.pack_edge_index(train_interactions)
        self.edge_index = torch.tensor(edge_index, dtype=torch.long).t().contiguous().to(self.device)
        self.edge_index = torch.cat((self.edge_index, self.edge_index[[1, 0]]), dim=1)

        # 初始化用户和物品的权重参数，并进行softmax归一化
        self.weight_u = nn.Parameter(nn.init.xavier_normal_(
            torch.tensor(np.random.randn(self.num_user, 2, 1), dtype=torch.float32, requires_grad=True)))
        self.weight_u.data = F.softmax(self.weight_u, dim=1)

        self.weight_i = nn.Parameter(nn.init.xavier_normal_(
            torch.tensor(np.random.randn(self.num_item, 2, 1), dtype=torch.float32, requires_grad=True)))
        self.weight_i.data = F.softmax(self.weight_i, dim=1)

        # 初始化物品索引和掩码相关的参数
        self.item_index = torch.zeros([self.num_item], dtype=torch.long)
        index = []
        for i in range(self.num_item):
            self.item_index[i] = i
            index.append(i)
        self.drop_percent = self.drop_rate
        self.single_percent = 1
        self.double_percent = 0

        drop_item = torch.tensor(
            np.random.choice(self.item_index, int(self.num_item * self.drop_percent), replace=False))
        drop_item_single = drop_item[:int(self.single_percent * len(drop_item))]

        self.dropv_node_idx_single = drop_item_single[:int(len(drop_item_single) * 1 / 3)]
        self.dropt_node_idx_single = drop_item_single[int(len(drop_item_single) * 2 / 3):]

        self.dropv_node_idx = self.dropv_node_idx_single
        self.dropt_node_idx = self.dropt_node_idx_single

        # 构建掩码数组以对物品进行掩码处理
        mask_cnt = torch.zeros(self.num_item, dtype=int).tolist()
        for edge in edge_index:
            mask_cnt[edge[1] - self.num_user] += 1
        mask_dropv = []
        mask_dropt = []
        for idx, num in enumerate(mask_cnt):
            temp_false = [False] * num
            temp_true = [True] * num
            mask_dropv.extend(temp_false) if idx in self.dropv_node_idx else mask_dropv.extend(temp_true)
            mask_dropt.extend(temp_false) if idx in self.dropt_node_idx else mask_dropt.extend(temp_true)

        edge_index = edge_index[np.lexsort(edge_index.T[1, None])]
        edge_index_dropv = edge_index[mask_dropv]
        edge_index_dropt = edge_index[mask_dropt]

        self.edge_index_dropv = torch.tensor(edge_index_dropv).t().contiguous().to(self.device)
        self.edge_index_dropt = torch.tensor(edge_index_dropt).t().contiguous().to(self.device)

        self.edge_index_dropv = torch.cat((self.edge_index_dropv, self.edge_index_dropv[[1, 0]]), dim=1)
        self.edge_index_dropt = torch.cat((self.edge_index_dropt, self.edge_index_dropt[[1, 0]]), dim=1)

        # 初始化MLP和GCN层
        self.MLP_user = nn.Linear(self.dim_latent * 2, self.dim_latent)

        # 初始化多模态GCN模型
        if self.v_feat is not None:
            # 视觉模态GCN分支
            self.v_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode, 
                           dim_latent=64, device=self.device, features=self.v_feat)
            # 噪声增强的视觉模态GCN分支（用于对比学习）
            self.v_gcn_n1 = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
                              dim_latent=64, device=self.device, features=self.v_feat)
            self.v_gcn_n2 = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
                              dim_latent=64, device=self.device, features=self.v_feat)
        
        if self.t_feat is not None:
            # 文本模态GCN分支
            self.t_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
                           dim_latent=64, device=self.device, features=self.t_feat)
            # 噪声增强的文本模态GCN分支（用于对比学习）
            self.t_gcn_n1 = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
                              dim_latent=64, device=self.device, features=self.t_feat)
            self.t_gcn_n2 = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
                              dim_latent=64, device=self.device, features=self.t_feat)

        # 可学习的ID特征嵌入
        self.id_feat = nn.Parameter(
            nn.init.xavier_normal_(
                torch.tensor(np.random.randn(self.n_items, self.dim_latent), 
                           dtype=torch.float32, requires_grad=True),
                gain=1
            ).to(self.device)
        )
        
        # ID模态GCN模型
        self.id_gcn = GCN(self.dataset, batch_size, num_user, num_item, dim_x, self.aggr_mode,
                        dim_latent=64, device=self.device, features=self.id_feat)

        # 结果嵌入参数初始化
        embed_init = lambda shape: nn.Parameter(
            nn.init.xavier_normal_(
                torch.tensor(np.random.randn(*shape), dtype=torch.float32), gain=1
            ).to(self.device)
        )
        
        # 多模态结果嵌入向量
        self.result_embed = embed_init([num_user + num_item, dim_x])      # 综合嵌入
        self.result_embed_guide = embed_init([num_user + num_item, dim_x])# 指导嵌入
        self.result_embed_v = embed_init([num_user + num_item, dim_x])    # 视觉嵌入
        self.result_embed_t = embed_init([num_user + num_item, dim_x])    # 文本嵌入
        self.result_embed_n1 = embed_init([num_user + num_item, dim_x])   # 噪声嵌入1
        self.result_embed_n2 = embed_init([num_user + num_item, dim_x])   # 噪声嵌入2

    def get_knn_adj_mat(self, mm_embeddings):
        # 对多模态嵌入进行L2归一化
        context_norm = F.normalize(mm_embeddings, p=2, dim=1)
        # 计算相似度矩阵
        sim = torch.mm(context_norm, context_norm.transpose(1, 0))
        # 获取top-k近邻索引
        _, knn_ind = torch.topk(sim, self.knn_k, dim=-1)
        # 构建稀疏邻接矩阵索引
        row_indices = torch.arange(knn_ind.shape[0], device=self.device).view(-1, 1).expand_as(knn_ind)
        flat_row = row_indices.contiguous().view(-1)
        flat_col = knn_ind.contiguous().view(-1)
        indices = torch.stack((flat_row, flat_col))
        # 返回索引和归一化拉普拉斯矩阵
        return indices, self.compute_normalized_laplacian(indices, sim.shape)

    def compute_normalized_laplacian(self, indices, adj_size):
        """
        根据给定的邻接矩阵索引(indices)和矩阵大小(adj_size)，构建归一化拉普拉斯矩阵。
        
        参数:
        - indices: 边的索引张量，形状为(2, E)，其中E是边的数量。
        - adj_size: 邻接矩阵的大小，通常为节点数。
        
        返回:
        - 归一化拉普拉斯矩阵，稀疏张量格式。
        """
        # 创建稀疏邻接矩阵，值初始化为1
        adj = torch.sparse.FloatTensor(indices, torch.ones_like(indices[0]), adj_size)
        
        # 计算每行的和（即每个节点的度数），并添加一个微小值以防止除以0
        row_sum = 1e-7 + torch.sparse.sum(adj, -1).to_dense()
        
        # 取度数的-0.5次方，用于归一化
        r_inv_sqrt = torch.pow(row_sum, -0.5)
        
        # 根据索引获取源节点和目标节点的归一化因子
        rows_inv_sqrt = r_inv_sqrt[indices[0]]  # 源节点
        cols_inv_sqrt = r_inv_sqrt[indices[1]]  # 目标节点
        
        # 归一化边的权重，采用源节点和目标节点的乘积
        values = rows_inv_sqrt * cols_inv_sqrt
        
        # 返回归一化后的稀疏拉普拉斯矩阵
        return torch.sparse.FloatTensor(indices, values, adj_size)

    def pre_epoch_processing(self):
        """
        在每个训练周期开始前，进行用户图的采样处理。
        """
        # 调用topk_sample方法生成用户图和对应的权重矩阵
        self.epoch_user_graph, self.user_weight_matrix = self.topk_sample(self.k)
        # 将权重矩阵移动到指定的设备（如GPU）
        self.user_weight_matrix = self.user_weight_matrix.to(self.device)

    def pack_edge_index(self, inter_mat):
        """
        将交互矩阵转换为边索引格式，便于图神经网络处理。
        
        参数:
        - inter_mat: scipy的coo_matrix格式的交互矩阵。
        
        返回:
        - edge_index: 边索引，形状为(E, 2)，其中E是边的数量。
        """
        # 获取用户和物品的交互行和列，并将物品索引偏移到用户之后
        rows = inter_mat.row
        cols = inter_mat.col + self.n_users
        
        # 合并为边索引数组并返回
        return np.column_stack((rows, cols))

    def InfoNCE(self, view1, view2, temp):
        """
        计算对比学习中的InfoNCE损失。
        
        参数:
        - view1: 第一个视图的嵌入向量。
        - view2: 第二个视图的嵌入向量。
        - temp: 温度参数，用于控制softmax的锐度。
        
        返回:
        - cl_loss: InfoNCE损失值。
        """
        # 对两个视图的嵌入进行L2归一化
        view1, view2 = F.normalize(view1, dim=1), F.normalize(view2, dim=1)
        
        # 计算正样本的相似度得分
        pos_score = (view1 * view2).sum(dim=-1)
        pos_score = torch.exp(pos_score / temp)
        
        # 计算所有样本的相似度得分，并求和
        ttl_score = torch.matmul(view1, view2.transpose(0, 1))
        ttl_score = torch.exp(ttl_score / temp).sum(dim=1)
        
        # 计算对比学习损失
        cl_loss = -torch.log(pos_score / ttl_score)
        return torch.mean(cl_loss)

    def forward(self, interaction):
        """
        前向传播函数，负责处理输入的交互数据，并生成用户和物品的嵌入表示。
        
        参数:
        - interaction: 包含用户、正样本物品和负样本物品索引的元组。
        
        返回:
        - pos_scores: 正样本物品的预测得分。
        - neg_scores: 负样本物品的预测得分。
        """

        # Step1：原始特征输入：用户、正/负物品节点（原始 ID，需转换为图中的全局节点 ID）
        user_nodes, pos_item_nodes, neg_item_nodes = interaction[0], interaction[1], interaction[2]
        # 物品节点 ID 偏移：区分用户和物品（用户节点范围 [0, n_users)，物品节点 = n_users + 原始物品 ID）
        pos_item_nodes += self.n_users
        neg_item_nodes += self.n_users

        # Step2：基于GCN对不同模态进行图形上的表示（视觉 + 文本 + ID）
        self.v_rep, self.v_preference = self.v_gcn(self.edge_index_dropv, self.edge_index, self.v_feat)
        self.t_rep, self.t_preference = self.t_gcn(self.edge_index_dropt, self.edge_index, self.t_feat)
        self.id_rep, self.id_preference = self.id_gcn(self.edge_index_dropt, self.edge_index, self.id_feat)

        # 对模型加入噪声增强（SimGCL想法）
        self.v_rep_n1, _ = self.v_gcn_n1(self.edge_index_dropv, self.edge_index, self.v_feat, perturbed=True)
        self.t_rep_n1, _ = self.t_gcn_n1(self.edge_index_dropt, self.edge_index, self.t_feat, perturbed=True)
        self.v_rep_n2, _ = self.v_gcn_n2(self.edge_index_dropv, self.edge_index, self.v_feat, perturbed=True)
        self.t_rep_n2, _ = self.t_gcn_n2(self.edge_index_dropt, self.edge_index, self.t_feat, perturbed=True)

        # Step3.1 模态融合（级联）：视觉+文本、ID 增强、视觉增强、文本增强
        representation = torch.cat((self.v_rep, self.t_rep), dim=1)
        guide_representation = torch.cat((self.id_rep, self.id_rep), dim=1)
        v_representation = torch.cat((self.v_rep, self.v_rep), dim=1)
        t_representation = torch.cat((self.t_rep, self.t_rep), dim=1)

        # 合并噪声表示
        representation_n1 = torch.cat((self.v_rep_n1, self.t_rep_n1), dim=1)
        representation_n2 = torch.cat((self.v_rep_n2, self.t_rep_n2), dim=1)

        # 维度扩展：从 [B, D] → [B, D, 1]，方便后续多模态拼接
        self.v_rep = torch.unsqueeze(self.v_rep, 2)
        self.t_rep = torch.unsqueeze(self.t_rep, 2)
        self.id_rep = torch.unsqueeze(self.id_rep, 2)

        # Step3.2 用户表示构建：取前 self.num_user 个样本（用户节点），拼接多模态特征并加权
        user_rep = torch.cat((self.v_rep[:self.num_user], self.t_rep[:self.num_user]), dim=2)
        user_rep = self.weight_u.transpose(1, 2) * user_rep  # 模态加权（可学习权重）
        user_rep = torch.cat((user_rep[:, :, 0], user_rep[:, :, 1]), dim=1)  # 合并表示

        # 同理构建其他视图的用户表示：ID增强 纯视觉 纯文本 基于GCN1/GCN2加入噪声的用户特征
        guide_user_rep = torch.cat((self.id_rep[:self.num_user], self.id_rep[:self.num_user]), dim=2)
        guide_user_rep = torch.cat((guide_user_rep[:, :, 0], guide_user_rep[:, :, 1]), dim=1)

        v_user_rep = torch.cat((self.v_rep[:self.num_user], self.v_rep[:self.num_user]), dim=2)
        v_user_rep = torch.cat((v_user_rep[:, :, 0], v_user_rep[:, :, 1]), dim=1)

        t_user_rep = torch.cat((self.t_rep[:self.num_user], self.t_rep[:self.num_user]), dim=2)
        t_user_rep = torch.cat((t_user_rep[:, :, 0], t_user_rep[:, :, 1]), dim=1)

        self.v_rep_n1 = torch.unsqueeze(self.v_rep_n1, 2)
        self.t_rep_n1 = torch.unsqueeze(self.t_rep_n1, 2)
        user_rep_n1 = torch.cat((self.v_rep_n1[:self.num_user], self.t_rep_n1[:self.num_user]), dim=2)
        user_rep_n1 = self.weight_u.transpose(1, 2) * user_rep_n1
        user_rep_n1 = torch.cat((user_rep_n1[:, :, 0], user_rep_n1[:, :, 1]), dim=1)

        self.v_rep_n2 = torch.unsqueeze(self.v_rep_n2, 2)
        self.t_rep_n2 = torch.unsqueeze(self.t_rep_n2, 2)
        user_rep_n2 = torch.cat((self.v_rep_n2[:self.num_user], self.t_rep_n2[:self.num_user]), dim=2)
        user_rep_n2 = self.weight_u.transpose(1, 2) * user_rep_n2
        user_rep_n2 = torch.cat((user_rep_n2[:, :, 0], user_rep_n2[:, :, 1]), dim=1)

        # Step3.3 物品表示构建：取剩余样本（物品节点），基于多视图特征 + 物品-物品图增强
        item_rep = representation[self.num_user:] # 基础 VT 融合
        item_rep_n1 = representation_n1[self.num_user:]
        item_rep_n2 = representation_n2[self.num_user:]

        guide_item_rep = guide_representation[self.num_user:]
        v_item_rep = v_representation[self.num_user:]
        t_item_rep = t_representation[self.num_user:]

        # 物品-物品图增强（对应流程图的 Item semantic graph）
        h = self.buildItemGraph(item_rep)
        h_guide = self.buildItemGraph(guide_item_rep)
        h_v = self.buildItemGraph(v_item_rep)
        h_t = self.buildItemGraph(t_item_rep)
        h_n1 = self.buildItemGraph(item_rep_n1)
        h_n2 = self.buildItemGraph(item_rep_n2)

        # 同理构建其他视图的物品表示（ID 增强、纯视觉、纯文本、噪声版）
        item_rep = item_rep + h # 融合物品语义图信息
        item_rep_n1 = item_rep_n1 + h_n1
        item_rep_n2 = item_rep_n2 + h_n2
        guide_item_rep = guide_item_rep + h_guide
        v_item_rep = v_item_rep + h_v
        t_item_rep = t_item_rep + h_t

        # 构建多视图的最终表示（用户+物品拼接）
        self.user_rep = user_rep
        self.item_rep = item_rep
        self.result_embed = torch.cat((user_rep, item_rep), dim=0) # 基础 VT 融合头

        self.guide_user_rep = guide_user_rep
        self.guide_item_rep = guide_item_rep
        self.result_embed_guide = torch.cat((guide_user_rep, guide_item_rep), dim=0)  # ID 增强头

        self.v_user_rep = v_user_rep
        self.v_item_rep = v_item_rep
        self.result_embed_v = torch.cat((v_user_rep, v_item_rep), dim=0) # 纯视觉头

        self.t_user_rep = t_user_rep
        self.t_item_rep = t_item_rep
        self.result_embed_t = torch.cat((t_user_rep, t_item_rep), dim=0) # 纯文本头

        self.user_rep_n1 = user_rep_n1
        self.item_rep_n1 = item_rep_n1
        self.result_embed_n1 = torch.cat((user_rep_n1, item_rep_n1), dim=0) # 噪声1头

        self.user_rep_n2 = user_rep_n2
        self.item_rep_n2 = item_rep_n2
        self.result_embed_n2 = torch.cat((user_rep_n2, item_rep_n2), dim=0) # 噪声2头

        # 从多视图表示中，提取用户、正/负物品的特征
        user_tensor = self.result_embed[user_nodes]
        pos_item_tensor = self.result_embed[pos_item_nodes]
        neg_item_tensor = self.result_embed[neg_item_nodes]
        # 计算得分：用户-物品点积（隐式假设“得分高的物品更匹配”）
        pos_scores = torch.sum(user_tensor * pos_item_tensor, dim=1)
        neg_scores = torch.sum(user_tensor * neg_item_tensor, dim=1)
        return pos_scores, neg_scores

    def buildItemGraph(self, h):
        """
        使用多层图卷积处理物品表示，每一层使用多模态邻接矩阵进行信息传播。

        参数:
        - h: 输入的物品表示向量。

        返回:
        - h: 经过图卷积处理的物品表示。
        """
        for i in range(self.n_layers):
            h = torch.sparse.mm(self.mm_adj, h)
        return h

    def fit_Gaussian_dis(self):
        """
        计算不同模态嵌入的均值和方差，用于后续的分布对齐损失计算。

        返回:
        - r_var, r_mean: 主嵌入的方差和均值。
        - g_var, g_mean: 指导嵌入的方差和均值。
        - v_var, v_mean: 视觉嵌入的方差和均值。
        - t_var, t_mean: 文本嵌入的方差和均值。
        """
        r_var = torch.var(self.result_embed)
        r_mean = torch.mean(self.result_embed)
        g_var = torch.var(self.result_embed_guide)
        g_mean = torch.mean(self.result_embed_guide)
        v_var = torch.var(self.result_embed_v)
        v_mean = torch.mean(self.result_embed_v)
        t_var = torch.var(self.result_embed_t)
        t_mean = torch.mean(self.result_embed_t)
        return r_var, r_mean, g_var, g_mean, v_var, v_mean, t_var, t_mean

    def calculate_loss(self, interaction):
        """
        计算模型的损失函数，包括推荐损失、正则化损失、掩码损失和对齐损失。

        参数:
        - interaction: 包含用户、正样本物品和负样本物品索引的元组。

        返回:
        - total_loss: 总损失值。
        """
        user = interaction[0]
        pos_scores, neg_scores = self.forward(interaction)

        # loss1 推荐损失：使用二元交叉熵损失
        loss_value = -torch.mean(torch.log2(torch.sigmoid(pos_scores - neg_scores)))

        # loss2 正则化损失：防止模型过拟合
        reg_embedding_loss_v = (self.v_preference[user] ** 2).mean() if self.v_preference is not None else 0.0
        reg_embedding_loss_t = (self.t_preference[user] ** 2).mean() if self.t_preference is not None else 0.0
        reg_loss = self.reg_weight * (reg_embedding_loss_v + reg_embedding_loss_t)
        reg_loss += self.reg_weight * (self.weight_u ** 2).mean()

        # loss3 掩码损失：通过对比学习增强表示学习
        with torch.no_grad():
            u_temp, i_temp = self.user_rep.clone(), self.item_rep.clone()
            u_temp2, i_temp2 = self.user_rep.clone(), self.item_rep.clone()
            u_temp.detach()
            i_temp.detach()
            u_temp2.detach()
            i_temp2.detach()
            u_temp2 = self.mlp(u_temp2)
            i_temp2 = self.mlp(i_temp2)
            u_temp = F.dropout(u_temp, self.dropout)
            i_temp = F.dropout(i_temp, self.dropout)
        mask_loss_u = 1 - F.cosine_similarity(u_temp, u_temp2).mean()
        mask_loss_i = 1 - F.cosine_similarity(i_temp, i_temp2).mean()
        mask_f_loss = self.mask_weight_f * (mask_loss_i + mask_loss_u)

        # loss4 对齐损失：对齐不同模态嵌入的分布
        r_var, r_mean, g_var, g_mean, v_var, v_mean, t_var, t_mean = self.fit_Gaussian_dis()

        align_loss = ((torch.abs(g_var - r_var) + torch.abs(g_mean - r_mean)).mean() +
                      (torch.abs(g_var - v_var) + torch.abs(g_mean - v_mean)).mean() +
                      (torch.abs(g_var - t_var) + torch.abs(g_mean - t_mean)).mean() +
                      (torch.abs(r_var - v_var) + torch.abs(r_mean - v_mean)).mean() +
                      (torch.abs(r_var - t_var) + torch.abs(r_mean - t_mean)).mean() +
                      (torch.abs(v_var - t_var) + torch.abs(v_mean - t_mean)).mean())

        # loss5 图噪声对比学习损失：增强模型鲁棒性
        mask_g_loss = (self.InfoNCE(self.result_embed_n1[:self.n_users], self.result_embed_n2[:self.n_users], self.temp) +
                       self.InfoNCE(self.result_embed_n1[self.n_users:], self.result_embed_n2[self.n_users:], self.temp))
        mask_g_loss = mask_g_loss * self.mask_weight_g

        # 加权总损失
        total_loss = loss_value + reg_loss + align_loss * self.align_weight + mask_f_loss + mask_g_loss
        return total_loss

    def full_sort_predict(self, interaction):
        # 获取所有用户和物品的嵌入表示
        user_tensor = self.result_embed[:self.n_users]
        item_tensor = self.result_embed[self.n_users:]

        # 根据当前交互的用户ID提取对应的用户嵌入
        temp_user_tensor = user_tensor[interaction[0], :]

        # 计算用户和物品嵌入之间的相似度得分矩阵
        score_matrix = torch.matmul(temp_user_tensor, item_tensor.t())
        return score_matrix

    def topk_sample(self, k):
        # 初始化用户图索引列表和权重矩阵
        user_graph_index = []
        user_weight_matrix = torch.zeros(len(self.user_graph_dict), k)

        # 遍历每个用户的图结构
        for i in range(len(self.user_graph_dict)):
            if len(self.user_graph_dict[i][0]) < k:
                # 如果邻居数量不足k，采用随机采样补充
                if len(self.user_graph_dict[i][0]) == 0:
                    # 如果没有邻居，使用全0索引填充
                    user_graph_index.append([0] * k)
                    continue
                # 截取前k个邻居
                user_graph_sample = self.user_graph_dict[i][0][:k]
                user_graph_weight = self.user_graph_dict[i][1][:k]
                # 填充不足k个的部分
                while len(user_graph_sample) < k:
                    rand_index = np.random.randint(0, len(user_graph_sample))
                    user_graph_sample.append(user_graph_sample[rand_index])
                    user_graph_weight.append(user_graph_weight[rand_index])
                # 对权重进行softmax归一化处理
                user_weight_matrix[i] = F.softmax(torch.tensor(user_graph_weight), dim=0)
                user_graph_index.append(user_graph_sample)
            else:
                # 如果邻居数量足够，直接截取前k个邻居并进行softmax处理
                user_graph_sample = self.user_graph_dict[i][0][:k]
                user_graph_weight = self.user_graph_dict[i][1][:k]
                user_weight_matrix[i] = F.softmax(torch.tensor(user_graph_weight), dim=0)
                user_graph_index.append(user_graph_sample)

        # 返回采样后的用户图索引和对应的权重矩阵
        return user_graph_index, user_weight_matrix

    def print_embd(self):
        # 返回视觉和文本模态的嵌入表示
        return self.result_embed_v, self.result_embed_t


class GCN(torch.nn.Module):
    def __init__(self, datasets, batch_size, num_user, num_item, dim_id, aggr_mode,
                 dim_latent=None, device=None, features=None):
        super(GCN, self).__init__()
        self.batch_size = batch_size
        self.num_user = num_user
        self.num_item = num_item
        self.datasets = datasets
        self.dim_id = dim_id
        self.dim_latent = dim_latent
        self.aggr_mode = aggr_mode
        self.device = device

        # 处理特征维度
        if features is not None:
            self.dim_feat = features.size(1)
        else:
            self.dim_feat = 0  # 默认值，防止未定义特征时出现错误

        # 如果dim_latent存在，使用潜在空间映射
        if self.dim_latent:
            # 初始化用户偏好参数
            self.preference = nn.Parameter(
                nn.init.xavier_normal_(
                    torch.tensor(np.random.randn(num_user, self.dim_latent), dtype=torch.float32, requires_grad=True),
                    gain=1
                ).to(self.device)
            )
            # 定义多层感知机（MLP）用于特征转换
            self.MLP = nn.Sequential(
                nn.Linear(self.dim_feat, 4 * self.dim_latent),
                nn.LeakyReLU(),
                nn.Linear(4 * self.dim_latent, self.dim_latent)
            )
            # 使用多层GCN进行信息传播
            self.conv_embed_layers = nn.ModuleList()
            num_layers = 2  # 设置GCN层数
            for _ in range(num_layers):
                self.conv_embed_layers.append(
                    Base_gcn(self.dim_latent, self.dim_latent, aggr=self.aggr_mode)
                )
        else:
            # 如果dim_latent不存在，直接使用特征维度
            self.preference = nn.Parameter(
                nn.init.xavier_normal_(
                    torch.tensor(np.random.randn(num_user, self.dim_feat), dtype=torch.float32, requires_grad=True),
                    gain=1
                ).to(self.device)
            )
            # 使用单层GCN
            self.conv_embed_layers = nn.ModuleList([
                Base_gcn(self.dim_feat, self.dim_feat, aggr=self.aggr_mode)
            ])

    def forward(self, edge_index_drop, edge_index, features, perturbed=False):
        # 如果dim_latent存在，则通过MLP处理特征
        if self.dim_latent:
            temp_features = self.MLP(features) if features is not None else torch.zeros(
                (self.num_item, self.dim_latent), device=self.device
            )
        else:
            temp_features = features if features is not None else torch.zeros(
                (self.num_item, self.dim_feat), device=self.device
            )

        # 拼接用户偏好和物品特征
        x = torch.cat((self.preference, temp_features), dim=0).to(self.device)
        x = F.normalize(x)

        # 通过GCN层传播
        h = x
        for conv_layer in self.conv_embed_layers:
            h = conv_layer(h, edge_index)
            if perturbed:
                # 添加扰动以增强鲁棒性
                random_noise = torch.randn_like(h).to(self.device)
                h += torch.sign(h) * F.normalize(random_noise, dim=-1) * 0.1

        # 最终输出
        x_hat = x + h  # 残差连接
        return x_hat, self.preference


class Base_gcn(MessagePassing):
    def __init__(self, in_channels, out_channels, normalize=True, bias=True, aggr='add', **kwargs):
        super(Base_gcn, self).__init__(aggr=aggr, **kwargs)
        self.aggr = aggr
        self.in_channels = in_channels
        self.out_channels = out_channels

        # 可学习的权重矩阵
        self.weight = nn.Parameter(torch.Tensor(in_channels, out_channels))
        self.reset_parameters()

    def reset_parameters(self):
        """初始化权重矩阵"""
        nn.init.xavier_uniform_(self.weight)

    def forward(self, x, edge_index, size=None):
        # 移除自环边
        if size is None:
            edge_index, _ = remove_self_loops(edge_index)

        x = x.unsqueeze(-1) if x.dim() == 1 else x
        return self.propagate(edge_index, size=(x.size(0), x.size(0)), x=x)

    def message(self, x_j, edge_index, size):
        row, col = edge_index
        # 计算度数的平方根倒数，用于归一化
        deg = degree(row, size[0], dtype=x_j.dtype)
        deg_inv_sqrt = deg.pow(-0.5)
        norm = deg_inv_sqrt[row] * deg_inv_sqrt[col]

        # 加权消息传递
        message = norm.view(-1, 1) * x_j
        message = torch.matmul(message, self.weight)
        return message

    def update(self, aggr_out):
        return aggr_out

    def __repr__(self):
        return '{}({}, {})'.format(self.__class__.__name__, self.in_channels, self.out_channels)
